PREFIX orn: <http://openrisknet.org/schema#>
# Only one query can be active at a time, the rest have to be commented out

# A very simple query the title of the Api:
#SELECT ?title
#WHERE {
#?tool orn:info ?info.
#?info orn:title ?title
#}

# Get all tripples that could be resolved using the JsonLd context
SELECT * {?s ?p ?o}

# Retrieves content based on "Use Cases for annotated APIs with Query Tool"
# a) service that can make a prediction


#SELECT ?service ?description ?method ?path ?paramsDescription ?paramsName ?paramsIn ?paramsSchema ?bodyContent ?bodyDescription ?bodyRequired ?contentSchema ?schemaProperties ?property ?contentProperty ?cType ?contentExample ?responseMimeType WHERE {
# service name
#?service a orn:Service.
# does a prediction
#?prediction a orn:Prediction.
# service path
# kind of prediction
#?prediction orn:summary|orn:description ?description;
# REST method
#orn:method ?method;
# collect subnodes
#orn:path ?path;
#orn:parameters ?parameters;
#orn:requestBody ?body;
#orn:responses ?responses.
# handle each subnode params body response
# parameters
#OPTIONAL {
#?parameters orn:description ?paramsDescription;
#orn:in ?paramsIn;
#orn:name ?paramsName;
#orn:schema ?pS.
#?pS orn:type ?paramsSchema.
#}
# body
#OPTIONAL {
#?body orn:content ?bodyContent;
#orn:description ?bodyDescription;
#orn:required ?bodyRequired.
#OPTIONAL { ?bodyContent ?p ?contentType. ?contentType orn:schema ?contentSchema.}
#OPTIONAL { ?bodyContent ?p ?contentType. ?contentType orn:schema ?contentSchema.
#?contentSchema orn:properties ?schemaProperties.
#?schemaProperties ?pr ?property.
#?property orn:property ?contentProperty;
#orn:example ?contentExample;
#orn:type ?cType.
#}
# response
#OPTIONAL {
#?responses orn:200 ?200.
#?200 orn:content ?returnContent.
#?returnContent ?pmime ?resmime.
#?resmime orn:returns ?responseMimeType.
#}
#}
#}
#ORDER BY ?path
